class NegativeNumberError(Exception):
    """Excepción personalizada para números negativos."""
    pass

def calcular_raiz_cubica(numero):
    if numero < 0:
        raise NegativeNumberError("Error: No se puede calcular la raíz cúbica de un número negativo.")
    
    return numero ** (1/3)

def main():
    # Lista de números de ejemplo
    numeros = [27, 8, -1, 64]

    for num in numeros:
        try:
            resultado = calcular_raiz_cubica(num)
            print(f"La raíz cúbica de {num} es {resultado}.")
        except NegativeNumberError as nne:
            print(nne)
        except Exception as e:
            print(f"Se produjo un error inesperado: {e}")

# Llamada a la función principal
if __name__ == "__main__":
    main()
